services:
  pgvector:
    image: pgvector/pgvector:pg18-trixie
    environment:
      POSTGRES_USER: chat-app
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chat_app
    ports:
      - "5432:5432"

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    depends_on:
      - redis

volumes:
  redis_insight_data:
